  
  pipeline {
    agent {
      node {
        label "Linux"
      } 
    }

    stages {
      stage('fetch_latest_code') {
        steps {
          git branch: 'main', credentialsId: 'b0ab10d5-3ec2-4fe7-8e2e-4cbb8784e350', url: 'https://github.com/liathoffman/Jenkins.git'
        }
      }
    
      stage('List files in repo on Unix Slave') {

      when {
        expression { isUnix() == true }
      }

      steps {      
        echo "Workspace location: ${env.WORKSPACE}"    
        sh 'ls -l'
      }
    }

      stage('TF Init&Plan') {
        steps {
          sh 'cd ${env.WORKSPACE}'
          sh 'terraform init'
          sh 'terraform plan'
        }      
      }

      stage('Approval') {
        steps {
          script {
            def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
          }
        }
      }

      stage('TF Apply') {
        steps {
          sh 'terraform apply -input=false'
        }
      }
    } 
  }